"""
stt.py
------
Speech-to-text backend. Per the challenge requirements we standardize
on Sarvam (Saaras v3) for STT, since it's optimized for the 22 Indian
languages that match the MSMARCO-XI dataset.

`SarvamSTT` below is the real integration (needs SARVAM_API_KEY and
network access to api.sarvam.ai, which this sandbox does not have).
`MockSTT` lets the rest of the pipeline (retrieval/generation/
guardrails/benchmarking) be built, tested, and demoed end-to-end
without live audio infrastructure -- it simply returns pre-supplied
text as if it had been transcribed, while still recording a realistic
STT latency figure for the benchmark report.
"""

from __future__ import annotations

import io
import os
import time

import av
import requests


def _convert_to_wav(webm_bytes: bytes) -> bytes:
    try:
        input_container = av.open(io.BytesIO(webm_bytes))
        output_io = io.BytesIO()
        output_container = av.open(output_io, mode='w', format='wav')
        in_stream = input_container.streams.audio[0]
        out_stream = output_container.add_stream('pcm_s16le', rate=16000)
        out_stream.channels = 1
        
        for frame in input_container.decode(in_stream):  # type: ignore
            for packet in out_stream.encode(frame):
                output_container.mux(packet)
                
        for packet in out_stream.encode(None):
            output_container.mux(packet)
            
        output_container.close()
        return output_io.getvalue()
    except Exception as e:
        # If it fails to parse as WebM, it might already be WAV, so return original bytes
        print("Warning: PyAV conversion failed, sending raw bytes.", e)
        return webm_bytes


class BaseSTT:
    def transcribe(self, audio_bytes: bytes, language_hint: str | None = None) -> tuple[str, float]:
        """Returns (transcript, latency_seconds)."""
        raise NotImplementedError


class SarvamSTT(BaseSTT):
    """
    Connects to Sarvam's Speech-to-Text API.
    Expects audio to be 16kHz WAV or PCM, but we'll send it assuming the pipeline
    has prepared it.
    """

    def __init__(self, api_key: str | None = None):
        self.api_key = api_key or os.environ.get("SARVAM_API_KEY")

    def transcribe(self, audio_bytes: bytes, language_hint: str | None = None) -> tuple[str, float]:
        import requests

        if not self.api_key:
            print("Warning: SARVAM_API_KEY not set. Cannot use Sarvam STT.")
            return "Transcript unavailable (no API key).", 0.0

        url = "https://api.sarvam.ai/speech-to-text"
        files = {'file': ('audio.wav', audio_bytes, 'audio/wav')}
        data = {'language': language_hint or 'hi-IN'}
        headers = {'api-subscription-key': self.api_key}

        t0 = time.perf_counter()
        response = requests.post(url, headers=headers, files=files, data=data)
        latency = time.perf_counter() - t0

        if response.status_code == 200:
            return response.json().get('transcript', ''), latency
        else:
            print(f"Sarvam STT failed: {response.text}")
            return "", latency


class MockSTT(BaseSTT):
    """Fallback offline mock for testing"""

    def __init__(self, simulated_latency_s: float = 0.5):
        self.simulated_latency_s = simulated_latency_s

    def transcribe(self, audio_bytes: bytes, language_hint: str | None = None) -> tuple[str, float]:
        t0 = time.perf_counter()
        try:
            # Check for dummy WAV generated by tests
            if len(audio_bytes) < 100: 
                time.sleep(self.simulated_latency_s)
                return "Mock transcript", time.perf_counter() - t0
        except Exception:
            pass
        time.sleep(self.simulated_latency_s)
        return "mock transcript for testing", time.perf_counter() - t0


def get_stt(backend: str | None = None) -> BaseSTT:
    backend = backend or os.environ.get("STT_BACKEND", "mock")
    if backend == "mock":
        return MockSTT()
    if backend == "sarvam":
        return SarvamSTT()
    raise ValueError(f"Unknown STT backend: {backend}")
